[project]
name = "uv-astral-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.1.0",
    "pytest>=8.3.3",
    "ruff>=0.6.8",
    "setuptools>=75.1.0",
    "tool>=0.8.0",
]
