name: Deploy Databricks Asset Bundle to Development

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup uv and databricks cli
      run: |
        make install
        uv build
    - name: Verify Databricks CLI installation
      run: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh
        echo "::add-path::/usr/local/bin"
        echo "PATH set to: $PATH"
        echo "::add-path::$HOME/bin"
        echo "PATH set to: $PATH"
        databricks -v
        which databricks
    - name: Set up Databricks CLI
      run: |
        databricks configure --token
      env:
        DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
    # Build and Deploy the asset bundle to Databricks
    - name: Deploy Databricks Asset Bundle
      run: |
        # Example command to create or update a Databricks job or other asset
        uv run databricks bundle deploy --target dev

    - name: Notify on success or failure
      if: failure()
      run: echo "Deployment to Databricks failed" || echo "Deployment successful"

    # Optional: Run unit tests after deployment (if applicable)
    - name: Run Unit Tests (Optional)
      run: |
        # Example to run tests
        python -m pytest demo_project/tests/